FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=senhaSegura123

ENV DB_TYPE=mongodb
ENV DB_MONGO_CONNECTION_URL=${MONGO_URI}

ENV N8N_DISABLE_PRODUCTION_MAIN_LOG=true
